runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  script: auto

env_variables:
  FIREBASE_CREDENTIALS: "smartfit-capstone-firebase-adminsdk.json"
  RAPIDAPI_KEY: "67f693bec0mshee568f9f9bf788dp10474ajsn78fa9faea472"
  RAPIDAPI_HOST: "real-time-amazon-data.p.rapidapi.com"
  RAPIDAPI_URL: "https://real-time-amazon-data.p.rapidapi.com/search"

instance_class: F2

automatic_scaling:
  max_instances: 3
  min_instances: 1